version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: hr_recruit_test
    ports:
      - "3307:3306"

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    environment:
      - DB_HOST=mysql-test
      - DB_PORT=3306
      - DB_NAME=hr_recruit_test
      - DB_USER=root
      - DB_PASSWORD=test_password
      - OPENAI_API_KEY=${OPENAI}
      - ENV=test
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql-test

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend-test:8000
      - NODE_ENV=test
