FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && \
    apt-get install -y pkg-config python3-dev default-libmysqlclient-dev build-essential && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["pytest", "-v"]
